-- Find total customers by state
SELECT
  customer_state,
  COUNT(customer_id) AS customers_from_state
FROM gold.dim_customers
GROUP BY customer_state
ORDER BY customers_from_state DESC;

-- What is the distribution of sold items across states?
SELECT 
customer_state,
items_per_state,
ROUND(items_per_state / SUM(items_per_state) OVER() * 100, 2) AS percent_of_total_items
  FROM (
  SELECT
    c.customer_state,
    COUNT(s.order_id) items_per_state
  FROM gold.dim_customers c
  INNER JOIN gold.fact_sales s
    ON s.customer_id = c.customer_id
  GROUP BY c.customer_state
)
ORDER BY items_per_state DESC;

-- Find total products by category
SELECT
  COALESCE(product_category_name, 'UNAVAILABLE') AS product_category_name,
  COUNT (product_id) AS products_per_category
FROM gold.dim_products
GROUP BY product_category_name
ORDER BY COUNT (product_id) DESC;


-- What is the average selling price in each category?
SELECT
  COALESCE(p.product_category_name, 'UNAVAILABLE') AS product_category_name,
  AVG(s.total_item_value) AS average_per_category
FROM gold.fact_sales s
INNER JOIN gold.dim_products p 
  ON p.product_id = s.product_id
GROUP BY p.product_category_name
ORDER BY AVG(s.total_item_value) DESC;

-- What is the total revenue generated for each category?
-- Find total revenue generated by each customer
-- Find total customers by payment type